# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - CSharpProject/*

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- checkout: self
 # Disable shallow fetch
  fetchDepth: 0

- task: SonarQubePrepare@7
  inputs:
    SonarQube: 'SonarQube Server-dotnet-example'
    scannerMode: 'dotnet'
    projectKey: 'onboarding-examples_dotnet-example'
    projectName: 'onboarding-examples_python-example'
    extraProperties: |
      # Additional properties that will be passed to the scanner, 
      # Put one key=value per line, example:
      # sonar.exclusions=**/*.bin
      sonar.verbose=true

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: 'project.sln' # Adjust this pattern to match your project file
    workingDirectory: .
  # Command Line task to run your build.

# Dotnet build task
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'project.sln'
    workingDirectory: .
  displayName: 'dotnet build'

# Run Code Analysis task
- task: SonarQubeAnalyze@7

# Publish Quality Gate Result task
- task: SonarQubePublish@7
  inputs:
    pollingTimeoutSec: '300'
